name: "web_app"
mode: "dev"
port: 8080
version: "v0.0.3"
start_time: "2022-09-26"
machine_id: 1
locale: "zh"
log:
  log_level: "debug"
  log_filename: "log.log"
  err_level: "error"
  err_filename: "err.log"
  filepath: "./log/"
  max_size: 200
  max_age: 30
  max_backups: 7
  compress: false
mysql:
  host: "127.0.0.1"
  port: 13306
  user: "root"
  password: "123456"
  db_name: "db1"
  max_open_conns: 100
  max_idle_conns: 10
redis:
  host: "127.0.0.1"
  port: 16379
  password: ""
  db: 0
  pool_size: 100